# .streamlit/secrets.toml

[mysql]
host = "mysql-3320ccae-kaiakun3-276d.c.aivencloud.com"
port = "18894"
user = "avnadmin"
password = "AVNS_-J8ArXe9DAZf2t4DHxz"
database = "defaultdb"
ssl_ca = "-----BEGIN CERTIFICATE-----
MIIEUDCCArigAwIBAgIUAUDr9RpoYsqCpbJIi+88XoGe6jcwDQYJKoZIhvcNAQEM
BQAwQDE+MDwGA1UEAww1MTI3YjYyMGUtZDczZC00YjdiLTg4YzMtOTQ0MmU0YThl
N2MwIEdFTiAxIFByb2plY3QgQ0EwHhcNMjUwNjEyMTkzOTM4WhcNMzUwNjEwMTkz
OTM4WjBAMT4wPAYDVQQDDDUxMjdiNjIwZS1kNzNkLTRiN2ItODhjMy05NDQyZTRh
OGU3YzAgR0VOIDEgUHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCC
AYoCggGBALaPdMrG8IXtOEQqVVqJaLtobwQQZyXEs8ecuPanF45gtqewh7joW/J3
mJFJbcMuCtqlhoohXLsI9fTi97+0vv+PVv+YFg962QkV0OQq8744vtTbzBOVW5fZ
+7xmFk7Ze62DEVicB9TzyLaSUl1IMMNZpxczTow6KFHMYlacKo4k+GPsEqXzKg8v
Z9cWiREuOSIFSk1LAaa0XTwafsIAVlMpKGuOM5MHnDGZ8ICPjcGsoUrye1gt54cE
tYhvXpOm6UJ1Lf7023cL+L3dyugo1uhks3qwnOpfWPWegPcp0cIVxeSExkqP4NEL
4UG+D1U7Ghg4bIDmnz63A0KKcCrT0DBpNTtgVC0NuKDCdlvGD2h1aEKp65Awxl6V
wVZ0deWUnyTB5gkyI84Y4upGB42KKqOijZY6cEHBSGoqvKkrWYdrzabj/rQ/6Mr0
OPjdb/ikfmfFsRuPO2xesEfNzSrtN6vGPzWfPfztQHdG08jxIMA791SltuI1Amf2
0GtcuO84HQIDAQABo0IwQDAdBgNVHQ4EFgQUIdx8Km6hgzGA0RFJdFQK+Ya+Vaow
EgYDVR0TAQH/BAgwBgEB/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQAD
ggGBAIGfIpjOSNdlEUVbXIaLtM0RHvyFd8tCYAj5P1kcxjBLcm6eXI+zdVho/VCM
7eaDSVGWsbl/vqTJQuM2k8+iZaIJmOv7CHYmrNGY6D3m9z71OHCg60JkPgL6zW23
FxbJcnj5tRgTQZtwrh4bqYe5sAgNHbkweTfbwInWKapMKAQG6VjFlHVElQejDa6n
i/jEW6ayq9Wiw56xjSlRovdb6ES7Gcr/Sjm4x2UGU81BxDxo1ab8KSL0UxXsY3V3
547soBETo4NteP4A7FyqmRhkrGk24i+L0ZmPa+z6TGlGe26ZA2q8tIBFghOQrW1L
H2ed4pFF5nrQeWtpiz59MjgLeDLU5OoBjbnzyUieeoB6njt6BjvQl7qRRIAZxPKt
Bz/pj1AtwO1trqTtPAXAAx5CryVU+1U2a+YjFbsaUK2bzgzOA2nE+i58vkp+staJ
CuaDLMhApNN63Y/ieTlN0S7sK7XwtTh8fanWzQfUTj+cvNgUs4osIRlBWoXujhng
D4I1Yw==
-----END CERTIFICATE-----
" # <--- INI PENTING! Ganti "ca.pem" kalau nama filenya beda
